<a href="https://colab.research.google.com/github/srushtipatil08/python-workshop/blob/main/basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. import numpy

In [ ]:
import numpy as np

2. Creating numpy as array

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#np. array
#import numpy as np
#a = np.array (1,2,3)
#print(a)
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
#2D and 3D
b =  np.array([[2,3],[5,6]])
print(b)

[[2 3]
 [5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
a = np.array([1,2,3,], dtype=np.uint8)
print(a)
print(a.dtype)

b = np.array([1,2,3], dtype=complex)
print(b)
print(b.dtype)

[1 2 3]
uint8
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [ ]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [ ]:
# #np.arange
np.arange(1,11,2)


array([1, 3, 5, 7, 9])

In [ ]:
#with reshape
np.arange(16).reshape(2,2,2,2,)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
 np.ones((1,2))

array([[1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random
np.random.random((3,4))

array([[0.7803742 , 0.33827868, 0.21269057, 0.67603486],
       [0.97141576, 0.0347454 , 0.31868363, 0.38310993],
       [0.18835394, 0.9223134 , 0.21135253, 0.82940272]])

In [ ]:
#np.linspace
np.linspace(-10,10,10,dtype=float)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

Array Attributes

In [7]:
import numpy as np
a1 = np.array([3,4,5,6,7])

In [8]:
a1 = np.array([3,4,5,6,7])

In [9]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
b = np.array([[1,2,3,],[4,5,6,]])
print(b)
b.ndim


[[1 2 3]
 [4 5 6]]


2

In [12]:
b = np.array([[1,2,3,],[4,5,6,]])
print(b)
b.shape


[[1 2 3]
 [4 5 6]]


(2, 3)

In [13]:
b = np.array([[1,2,3,],[4,5,6,]])
print(b)
b.size

[[1 2 3]
 [4 5 6]]


6

In [14]:
b = np.array([[1,2,3,],[4,5,6,]])
print(b)
b.dtype

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [16]:
b = np.array([[1,2,3,],[4,5,6,]])
print(b)
b.itemsize

[[1 2 3]
 [4 5 6]]


8

In [17]:
b = np.array([[1,2,3,],[4,5,6,]])
print(b)
b.nbytes

[[1 2 3]
 [4 5 6]]


48

In [18]:
a=np.arange(12)
a.ndim

1

In [19]:
# ndim
a3.ndim

3

In [20]:
a1.shape

(10,)

In [21]:
a2.shape

(3, 4)

In [22]:
a3.dtype

dtype('int64')

Changing Datatype

In [23]:
# astype
a3.astype(np.int32)
a3.astype(np.float32).dtype

dtype('float32')

Array Operations

In [25]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
# scalar operations

# arithmatic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [27]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [28]:
# vector operations
# arithmatic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

Array Functions

In [29]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[66., 21., 89.],
       [21.,  3., 81.],
       [77., 92., 99.]])

In [32]:
#max/min/sum/np.prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([106722.,   5796., 713691.])

In [33]:
# mean/median/std/var
np.sin(a1)

array([[-0.02655115,  0.83665564,  0.86006941],
       [ 0.83665564,  0.14112001, -0.62988799],
       [ 0.99952016, -0.77946607, -0.99920683]])

In [34]:
# angle array in degrees
angles_deg = np.array([0, 30, 45, 60, 90])
# convert to radians
angles_rad = np.deg2rad(angles_deg)

print("angles in degrees:", angles_deg)
print("angles in radians:", angles_rad)

print("Sine:", np.sin(angles_rad))
print("Cosine:", np.cos(angles_rad))
print("Tangent:", np.tan(angles_rad))



angles in degrees: [ 0 30 45 60 90]
angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [36]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [37]:
# log and exponents
np.exp(a1)

array([[4.60718663e+28, 1.31881573e+09, 4.48961282e+38],
       [1.31881573e+09, 2.00855369e+01, 1.50609731e+35],
       [2.75851345e+33, 9.01762841e+39, 9.88903032e+42]])

In [38]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[ 8., 52., 50.],
       [42., 77., 57.]])